-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2024-03-11 08:52:59.232

-- tables
-- Table: ARTICLES
CREATE TABLE ARTICLES (
    id int  NOT NULL AUTO_INCREMENT,
    title Text  NOT NULL,
    content Text  NOT NULL,
    date_created datetime  NOT NULL,
    USERS_id int  NOT NULL,
    CONSTRAINT ARTICLES_pk PRIMARY KEY (id)
);

-- Table: COMMENTS
CREATE TABLE COMMENTS (
    id int  NOT NULL AUTO_INCREMENT,
    content Text  NOT NULL,
    ARTICLES_id int  NOT NULL,
    USERS_id int  NOT NULL,
    CONSTRAINT COMMENTS_pk PRIMARY KEY (id)
);

-- Table: USERS
CREATE TABLE USERS (
    id int  NOT NULL AUTO_INCREMENT,
    email Text  NOT NULL,
    CONSTRAINT USERS_pk PRIMARY KEY (id)
);

-- Table: USERS_USERS
CREATE TABLE USERS_USERS (
    USERS_id1 int  NOT NULL,
    USERS_id2 int  NOT NULL,
    CONSTRAINT USERS_USERS_pk PRIMARY KEY (USERS_id1,USERS_id2)
);

-- foreign keys
-- Reference: ARTICLES_COMMENTS (table: COMMENTS)
ALTER TABLE COMMENTS ADD CONSTRAINT ARTICLES_COMMENTS FOREIGN KEY ARTICLES_COMMENTS (ARTICLES_id)
    REFERENCES ARTICLES (id)
    ON DELETE CASCADE;

-- Reference: ARTICLES_USERS (table: ARTICLES)
ALTER TABLE ARTICLES ADD CONSTRAINT ARTICLES_USERS FOREIGN KEY ARTICLES_USERS (USERS_id)
    REFERENCES USERS (id)
    ON DELETE CASCADE;

-- Reference: USERS_COMMENTS (table: COMMENTS)
ALTER TABLE COMMENTS ADD CONSTRAINT USERS_COMMENTS FOREIGN KEY USERS_COMMENTS (USERS_id)
    REFERENCES USERS (id)
    ON DELETE CASCADE;

-- Reference: USERS_USERS_USERS (table: USERS_USERS)
ALTER TABLE USERS_USERS ADD CONSTRAINT USERS_USERS_USERS FOREIGN KEY USERS_USERS_USERS (USERS_id1)
    REFERENCES USERS (id)
    ON DELETE CASCADE;

-- Reference: USERS_USERS_USERS_2 (table: USERS_USERS)
ALTER TABLE USERS_USERS ADD CONSTRAINT USERS_USERS_USERS_2 FOREIGN KEY USERS_USERS_USERS_2 (USERS_id2)
    REFERENCES USERS (id)
    ON DELETE CASCADE;

-- End of file.

